name: Atlas CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: atlas_app
          POSTGRES_PASSWORD: atlas_test_password
          POSTGRES_DB: atlas_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U atlas_app -d atlas_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: app/backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run database migrations
        env:
          DATABASE_URL: postgresql+psycopg://atlas_app:atlas_test_password@localhost:5432/atlas_test
        run: alembic upgrade head

      - name: Run tests
        env:
          DATABASE_URL: postgresql+psycopg://atlas_app:atlas_test_password@localhost:5432/atlas_test
          TEST_DATABASE_URL: postgresql+psycopg://atlas_app:atlas_test_password@localhost:5432/atlas_test
        run: pytest

  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/mohameddmostafaa/atlas:latest
            ghcr.io/mohameddmostafaa/atlas:${{ github.sha }}



  docker-integration:
    name: Docker Compose Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Check running containers
        run: docker compose ps

      - name: Run database migrations
        run: docker compose exec -T api alembic upgrade head

      - name: Wait for API health
        run: |
          for i in {1..30}; do
            if curl --fail http://127.0.0.1:8000/health; then
              exit 0
            fi
            echo "API not ready yet..."
            sleep 2
          done

          echo "API failed to become ready"
          exit 1

      - name: Check API root
        run: curl --fail http://127.0.0.1:8000/

      - name: Show container logs
        if: always()
        run: docker compose logs

      - name: Stop Docker Compose
        if: always()
        run: docker compose down -v


  deploy:
    needs:
      - test
      - docker-build
      - docker-integration

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::034703319119:role/AtlasGitHubDeployRole
          aws-region: eu-central-1

      - name: Deploy to EC2
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids i-043a6f6e6e04cbab3 \
            --document-name AWS-RunShellScript \
            --parameters 'commands=["cd ~/atlas && ./deploy.sh"]' \
            --query 'Command.CommandId' \
            --output text)

          echo "SSM command: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id i-043a6f6e6e04cbab3

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id i-043a6f6e6e04cbab3 \
            --query '{Status:Status,Output:StandardOutputContent,Error:StandardErrorContent}' \
            --output yaml
